import type { SectorConfig } from "@/lib/types";

/**
 * MarineWorld.City — sector configuration for the Sector City Framework.
 * sector = marine-maritime
 *
 * All landing-page content renders from this configuration.
 * A future sector city (e.g. AutomotiveWorld.City) ships a different
 * configuration object — the UI architecture stays identical.
 */
export const marineSector: SectorConfig = {
  sectorId: "MARINE & MARITIME",
  sectorCode: "SECTOR CITY 001",
  sectorName: "MarineWorld",
  sectorTld: ".City",
  wordmark: "MarineWorld.City",
  tagline: "The digital business city for the global marine industry.",

  nav: [
    { label: "Explore", href: "#explorer" },
    { label: "Industries", href: "#intelligence" },
    { label: "Companies", href: "#network" },
    { label: "AI", href: "#ai" },
    { label: "Network", href: "#global" },
    { label: "About", href: "#governance" },
  ],

  hero: {
    eyebrow: "AI-NATIVE INDUSTRY INFRASTRUCTURE",
    statement: "THE AI-NATIVE BUSINESS CITY FOR THE GLOBAL MARITIME INDUSTRY.",
    accentPhrase: "MARITIME",
    support:
      "Build your AI-Native Company, activate its intelligence, and connect with customers, products, services and industry intelligence across the global maritime ecosystem — one governed digital city.",
    primaryCta: "CREATE YOUR AI-NATIVE COMPANY",
    secondaryCta: "EXPLORE MARINEWORLD",
    trust: [
      {
        index: "01",
        title: "BUILD YOUR AI-NATIVE COMPANY",
        desc: "Create and operate your company's digital identity.",
      },
      {
        index: "02",
        title: "ACTIVATE YOUR COMPANY AI",
        desc: "Teach your Company Brain and activate its intelligence.",
      },
      {
        index: "03",
        title: "CONNECT & TRADE GLOBALLY",
        desc: "Publish, get discovered, receive RFQs and do business.",
      },
    ],
    visualMeta: {
      coords: "36°53′N 30°42′E",
      label: "SHIPYARD DISTRICT — LIVE REGISTRY",
    },
    nodes: [
      {
        id: "port",
        icon: "gantry",
        title: "PORT.CITY",
        line: "Terminal operations — registry live",
      },
      {
        id: "rfq",
        icon: "doc",
        title: "RFQ · ENGINEERING.CITY",
        line: "Propulsion refit — routed to suppliers",
      },
      {
        id: "twin",
        icon: "twin",
        title: "AI TWIN ACTIVE",
        line: "Verified entity — responding for its company",
      },
    ],
  },

  activityFeed: [
    "RFQ · PROPULSION REFIT — ROUTED TO SHIPYARD.CITY",
    "VERIFIED · CORPORATE IDENTITY ISSUED — MARINA.CITY",
    "AI TWIN ACTIVATED — CHARTER OPERATOR, MEDITERRANEAN",
    "SERVICE REQUEST · HULL SURVEY — SUBSEA.CITY",
    "PRODUCT SPECIFICATION SERVED BY AI — MARINECOMMERCE.CITY",
    "CONNECTION · BROKER ↔ SHIPYARD — YACHTSALES.CITY",
    "TENDER PUBLISHED — PROCUREMENT.CITY",
    "CREW AVAILABILITY SYNCED — FLEETMANAGEMENT.CITY",
  ],

  intelligence: {
    eyebrow: "Industry Intelligence",
    headline: "THE MARITIME INDUSTRY, CONNECTED AS ONE DIGITAL CITY.",
    lead: "Maritime business lives in fragments — yards, ports, brokers, suppliers, financiers, each operating alone. MarineWorld structures the entire industry into one connected digital environment, where every domain is a live node in the same system.",
    domains: [
      { id: "companies", label: "Companies", meta: "Registry", icon: "building" },
      { id: "products", label: "Products", meta: "Index", icon: "cube" },
      { id: "services", label: "Services", meta: "Directory", icon: "briefcase" },
      { id: "ports", label: "Ports", meta: "Operations", icon: "gantry" },
      { id: "marinas", label: "Marinas", meta: "Berthing", icon: "dock" },
      { id: "shipyards", label: "Shipyards", meta: "Production", icon: "crane" },
      { id: "technology", label: "Technology", meta: "Innovation", icon: "chip" },
      { id: "finance", label: "Finance", meta: "Capital", icon: "chart" },
      { id: "legal", label: "Legal", meta: "Admiralty", icon: "scales" },
      { id: "crew", label: "Crew & Workforce", meta: "Talent", icon: "crew" },
      { id: "associations", label: "Associations", meta: "Institutions", icon: "flag" },
      { id: "ai", label: "AI Layer", meta: "Intelligence", icon: "chip" },
    ],
    caption:
      "Every node shares one identity system, one registry and one AI layer — so industry activity becomes discoverable, verifiable and operational.",
  },

  explorer: {
    eyebrow: "Sector City Explorer",
    headline: "EXPLORE THE MARITIME CITY.",
    lead: "MarineWorld is organized as a city of operational domains. Each city is a structured business environment with its own registry, companies, products and services.",
    note: "A curated selection of the MarineWorld registry is shown here. The complete registry is accessible through the explorer inside the platform.",
    cities: [
      {
        id: "marinecommerce",
        slug: "marinecommerce",
        domain: "MARINECOMMERCE.CITY",
        code: "REG 01",
        industryDomainId: "maritime-services",
        category: "Maritime Services, Ports, Marinas & Operations",
        description: "Marine equipment, parts and industrial trade across the global market.",
        shortDescription: "Marine equipment, parts and industrial trade.",
        icon: "exchange",
        scope: ["Equipment & parts trade", "Supplier catalogues", "Trade matchmaking"],
      },
      {
        id: "procurement",
        slug: "procurement",
        domain: "PROCUREMENT.CITY",
        code: "REG 02",
        industryDomainId: "maritime-services",
        category: "Maritime Services, Ports, Marinas & Operations",
        description: "Sourcing, tenders and supplier matching for maritime operations.",
        shortDescription: "Sourcing, tenders and supplier matching.",
        icon: "send",
        scope: ["Structured RFQs", "Tender publication", "Supplier qualification"],
      },
      {
        id: "supplychain",
        slug: "supplychain",
        domain: "SUPPLYCHAIN.CITY",
        code: "REG 03",
        industryDomainId: "maritime-services",
        category: "Maritime Services, Ports, Marinas & Operations",
        description: "End-to-end maritime supply chain visibility and coordination.",
        shortDescription: "End-to-end supply chain visibility.",
        icon: "route",
        scope: ["Logistics coordination", "Provisioning", "Spares distribution"],
      },
      {
        id: "yachtsales",
        slug: "yachtsales",
        domain: "YACHTSALES.CITY",
        code: "REG 04",
        industryDomainId: "vessel-sales",
        category: "Yachting, Charter & Maritime Lifestyle",
        description: "Yacht brokerage, sales networks and listing intelligence.",
        shortDescription: "Yacht brokerage, sales networks and listing intelligence.",
        icon: "sail",
        scope: ["Brokerage network", "Listings & valuations", "Buyer discovery"],
      },
      {
        id: "shipyard",
        slug: "shipyard",
        domain: "SHIPYARD.CITY",
        code: "REG 05",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Shipbuilding, repair and industrial marine production.",
        shortDescription: "Shipbuilding, repair and industrial marine production.",
        icon: "crane",
        scope: ["New builds", "Repair & refit", "Industrial capacity"],
      },
      {
        id: "boatbuilding",
        slug: "boatbuilding",
        domain: "BOATBUILDING.CITY",
        code: "REG 06",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Boatbuilders, refit specialists and craft production.",
        shortDescription: "Boatbuilders, refit specialists and craft production.",
        icon: "ship",
        scope: ["Custom builds", "Refit specialists", "Composite & wood craft"],
      },
      {
        id: "engineering",
        slug: "engineering",
        domain: "ENGINEERING.CITY",
        code: "REG 07",
        industryDomainId: "engineering-design",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Naval architecture and marine engineering services.",
        shortDescription: "Naval architecture and marine engineering.",
        icon: "drafting",
        scope: ["Naval architecture", "Systems engineering", "Survey & classification liaison"],
      },
      {
        id: "charter",
        slug: "charter",
        domain: "CHARTER.CITY",
        code: "REG 08",
        industryDomainId: "yachting-lifestyle",
        category: "Yachting, Charter & Maritime Lifestyle",
        description: "Charter operations across commercial and leisure fleets.",
        shortDescription: "Charter operations across commercial and leisure fleets.",
        icon: "sail",
        scope: ["Crewed & bareboat charter", "Commercial charter", "Fleet availability"],
      },
      {
        id: "marina",
        slug: "marina",
        domain: "MARINA.CITY",
        code: "REG 09",
        industryDomainId: "infrastructure",
        category: "Maritime Services, Ports, Marinas & Operations",
        description: "Berthing, marina services and waterfront infrastructure.",
        shortDescription: "Berthing, marina services and waterfront infrastructure.",
        icon: "dock",
        scope: ["Berth management", "Marina services", "Waterfront development"],
      },
      {
        id: "port",
        slug: "port",
        domain: "PORT.CITY",
        code: "REG 10",
        industryDomainId: "infrastructure",
        category: "Maritime Services, Ports, Marinas & Operations",
        description: "Ports, terminals and cargo operations.",
        shortDescription: "Ports, terminals and cargo operations.",
        icon: "gantry",
        scope: ["Terminal operations", "Agency services", "Cargo handling"],
      },
      {
        id: "fleetmanagement",
        slug: "fleetmanagement",
        domain: "FLEETMANAGEMENT.CITY",
        code: "REG 11",
        industryDomainId: "vessel-operations",
        category: "Maritime Services, Ports, Marinas & Operations",
        description: "Fleet management, crewing and vessel operations.",
        shortDescription: "Fleet management, crewing and vessel operations.",
        icon: "helm",
        scope: ["Technical management", "Crewing", "Vessel operations"],
      },
      {
        id: "marineai",
        slug: "marineai",
        domain: "MARINEAI.CITY",
        code: "REG 12",
        industryDomainId: "marine-technology",
        category: "Maritime Technology & AI Systems",
        description: "AI systems, agents and intelligence for maritime business.",
        shortDescription: "AI systems and intelligence for maritime business.",
        icon: "chip",
        scope: ["Industry AI agents", "Decision intelligence", "AI-native companies"],
      },
      {
        id: "digitaltwin",
        slug: "digitaltwin",
        domain: "DIGITALTWIN.CITY",
        code: "REG 13",
        industryDomainId: "marine-technology",
        category: "Maritime Technology & AI Systems",
        description: "Operational digital twins for vessels, ports and infrastructure.",
        shortDescription: "Operational digital twins for vessels and ports.",
        icon: "twin",
        scope: ["Vessel twins", "Port twins", "Asset lifecycle data"],
      },
      {
        id: "marinedata",
        slug: "marinedata",
        domain: "MARINEDATA.CITY",
        code: "REG 14",
        industryDomainId: "marine-technology",
        category: "Maritime Technology & AI Systems",
        description: "Maritime data services, feeds and analytics infrastructure.",
        shortDescription: "Maritime data services and analytics infrastructure.",
        icon: "database",
        scope: ["Data services", "Market intelligence", "Vessel & port data"],
      },
      {
        id: "autonomousvessel",
        slug: "autonomousvessel",
        domain: "AUTONOMOUSVESSEL.CITY",
        code: "REG 15",
        industryDomainId: "marine-technology",
        category: "Maritime Technology & AI Systems",
        description: "Autonomous and remotely operated vessels.",
        shortDescription: "Autonomous and remotely operated vessels.",
        icon: "radar",
        scope: ["Autonomous navigation", "Remote operations", "Testing & certification"],
      },
      {
        id: "marinecybersecurity",
        slug: "marinecybersecurity",
        domain: "MARINECYBERSECURITY.CITY",
        code: "REG 16",
        industryDomainId: "marine-technology",
        category: "Maritime Technology & AI Systems",
        description: "Cybersecurity for vessels, ports and maritime systems.",
        shortDescription: "Cybersecurity for vessels, ports and systems.",
        icon: "shield",
        scope: ["Vessel cyber defense", "Port systems security", "Compliance readiness"],
      },
      {
        id: "yachtfinance",
        slug: "yachtfinance",
        domain: "YACHTFINANCE.CITY",
        code: "REG 17",
        industryDomainId: "finance-legal",
        category: "Legal, Finance & Compliance",
        description: "Financing, leasing and capital structures for marine assets.",
        shortDescription: "Financing, leasing and capital structures.",
        icon: "chart",
        scope: ["Asset financing", "Leasing structures", "Capital introductions"],
      },
      {
        id: "insuranceops",
        slug: "insuranceops",
        domain: "INSURANCEOPS.CITY",
        code: "REG 18",
        industryDomainId: "finance-legal",
        category: "Legal, Finance & Compliance",
        description: "Marine insurance, P&I and risk operations.",
        shortDescription: "Marine insurance, P&I and risk operations.",
        icon: "lifebuoy",
        scope: ["Hull & machinery", "P&I services", "Claims support"],
      },
      {
        id: "marinelegal",
        slug: "marinelegal",
        domain: "MARINELEGAL.CITY",
        code: "REG 19",
        industryDomainId: "finance-legal",
        category: "Legal, Finance & Compliance",
        description: "Admiralty law, contracts and maritime compliance.",
        shortDescription: "Admiralty law, contracts and maritime compliance.",
        icon: "scales",
        scope: ["Admiralty & shipping law", "Contract advisory", "Regulatory compliance"],
      },
      {
        id: "offshore",
        slug: "offshore",
        domain: "OFFSHORE.CITY",
        code: "REG 20",
        industryDomainId: "offshore-subsea",
        category: "Offshore, Energy & Subsea",
        description: "Offshore energy, platforms and marine operations.",
        shortDescription: "Offshore energy, platforms and marine operations.",
        icon: "rig",
        scope: ["Offshore energy", "Platform services", "Marine operations"],
      },
      {
        id: "subsea",
        slug: "subsea",
        domain: "SUBSEA.CITY",
        code: "REG 21",
        industryDomainId: "offshore-subsea",
        category: "Offshore, Energy & Subsea",
        description: "Subsea engineering, survey and intervention.",
        shortDescription: "Subsea engineering, survey and intervention.",
        icon: "sonar",
        scope: ["Survey & inspection", "ROV intervention", "Subsea construction"],
      },
      {
        id: "marinelifestyle",
        slug: "marinelifestyle",
        domain: "MARINELIFESTYLE.CITY",
        code: "REG 22",
        industryDomainId: "lifestyle-hospitality",
        category: "Yachting, Charter & Maritime Lifestyle",
        description: "Marine lifestyle brands, experiences and waterfront culture.",
        shortDescription: "Marine lifestyle brands and waterfront culture.",
        icon: "sunrise",
        scope: ["Lifestyle brands", "Waterfront experiences", "Events & culture"],
      },
      {
        id: "marinehospitality",
        slug: "marinehospitality",
        domain: "MARINEHOSPITALITY.CITY",
        code: "REG 23",
        industryDomainId: "lifestyle-hospitality",
        category: "Real Estate & Hospitality",
        description: "Maritime hospitality, superyacht services and provisioning.",
        shortDescription: "Maritime hospitality, superyacht services.",
        icon: "flag",
        scope: ["Superyacht services", "Provisioning", "Crew hospitality"],
      },
      {
        id: "brokerage",
        slug: "brokerage",
        domain: "BROKERAGE.CITY",
        code: "REG 24",
        industryDomainId: "maritime-services",
        category: "Maritime Services, Ports, Marinas & Operations",
        description: "Commercial ship brokerage, cargo chartering, and vessel sale & purchase.",
        shortDescription: "Commercial ship brokerage and vessel S&P.",
        icon: "exchange",
        scope: ["Commercial S&P", "Cargo chartering", "Vessel valuation"],
      },
      {
        id: "propulsion",
        slug: "propulsion",
        domain: "PROPULSION.CITY",
        code: "REG 25",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Marine diesel engines, electric propulsion, pod drives, and shaft alignment services.",
        shortDescription: "Marine propulsion, engines and drive systems.",
        icon: "anchor",
        scope: ["Marine engines & gen-sets", "Electric & hybrid drives", "Pod drives & shafting"],
      },
      {
        id: "fabrication",
        slug: "fabrication",
        domain: "FABRICATION.CITY",
        code: "REG 26",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Marine steel, structural, mechanical and custom fabrication.",
        shortDescription: "Marine steel, structural, mechanical and custom fabrication.",
        icon: "crane",
        scope: ["Marine steel fabrication", "Custom structural welding", "Mechanical assemblies"],
      },
      {
        id: "steelworks",
        slug: "steelworks",
        domain: "STEELWORKS.CITY",
        code: "REG 27",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Marine steel structures, plates, blocks and heavy steel production.",
        shortDescription: "Marine steel structures, plates, blocks and heavy steel production.",
        icon: "ship",
        scope: ["Hull block fabrication", "Heavy marine steel plates", "Structural steel cutting"],
      },
      {
        id: "aluminiumworks",
        slug: "aluminiumworks",
        domain: "ALUMINIUMWORKS.CITY",
        code: "REG 28",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Marine aluminium structures, hulls and components.",
        shortDescription: "Marine aluminium structures, hulls and components.",
        icon: "drafting",
        scope: ["Aluminium hull construction", "Superstructure fabrication", "Lightweight marine alloys"],
      },
      {
        id: "composites",
        slug: "composites",
        domain: "COMPOSITES.CITY",
        code: "REG 29",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "GRP, CFRP and advanced composite marine structures and components.",
        shortDescription: "GRP, CFRP and advanced composite marine structures and components.",
        icon: "layers",
        scope: ["Carbon fibre tooling", "Infusion resin systems", "Composite sandwich panels"],
      },
      {
        id: "marinematerials",
        slug: "marinematerials",
        domain: "MARINEMATERIALS.CITY",
        code: "REG 30",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Marine-grade materials, coatings, insulation, consumables and industrial materials.",
        shortDescription: "Marine-grade materials, coatings, insulation and consumables.",
        icon: "cube",
        scope: ["Foul-release coatings", "Thermal & acoustic insulation", "Marine fasteners & consumables"],
      },
      {
        id: "hullsystems",
        slug: "hullsystems",
        domain: "HULLSYSTEMS.CITY",
        code: "REG 31",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Hull structures, appendages, tanks, doors, hatches and structural marine systems.",
        shortDescription: "Hull structures, appendages, tanks, doors and hatches.",
        icon: "ship",
        scope: ["Watertight doors & hatches", "Integrator tanks & bulkheads", "Hull appendages & rudders"],
      },
      {
        id: "marineequipment",
        slug: "marineequipment",
        domain: "MARINEEQUIPMENT.CITY",
        code: "REG 32",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Marine machinery and equipment including pumps, valves, compressors, deck machinery and onboard equipment.",
        shortDescription: "Marine machinery and equipment including pumps, valves and compressors.",
        icon: "box",
        scope: ["Auxiliary pumps & valves", "Air compressors & purifiers", "Onboard fluid machinery"],
      },
      {
        id: "marineelectrical",
        slug: "marineelectrical",
        domain: "MARINEELECTRICAL.CITY",
        code: "REG 33",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Marine electrical equipment, switchboards, distribution, cabling, converters, transformers and electrical panels.",
        shortDescription: "Marine electrical equipment, switchboards, cabling and distribution.",
        icon: "sliders",
        scope: ["Main switchboards & distribution", "Marine cabling & converters", "Shore power transformers"],
      },
      {
        id: "marineautomation",
        slug: "marineautomation",
        domain: "MARINEAUTOMATION.CITY",
        code: "REG 34",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Marine automation, vessel control systems, monitoring, alarm and integrated automation systems.",
        shortDescription: "Marine automation, vessel control systems, monitoring and alarms.",
        icon: "gauge",
        scope: ["Integrated bridge systems", "Engine alarm & monitoring", "Automated valve control"],
      },
      {
        id: "batterysystems",
        slug: "batterysystems",
        domain: "BATTERYSYSTEMS.CITY",
        code: "REG 35",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Marine batteries, energy storage and battery systems.",
        shortDescription: "Marine batteries, energy storage and battery systems.",
        icon: "gauge",
        scope: ["Lithium energy storage containers", "BMS battery management", "Peak-shaving marine packs"],
      },
      {
        id: "hybridpropulsion",
        slug: "hybridpropulsion",
        domain: "HYBRIDPROPULSION.CITY",
        code: "REG 36",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Hybrid marine propulsion systems and integration.",
        shortDescription: "Hybrid marine propulsion systems and integration.",
        icon: "anchor",
        scope: ["Diesel-electric hybrid drives", "PTI/PTO shaft generators", "Hybrid propulsion integration"],
      },
      {
        id: "powermanagement",
        slug: "powermanagement",
        domain: "POWERMANAGEMENT.CITY",
        code: "REG 37",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Marine power distribution, energy management and electrical control systems.",
        shortDescription: "Marine power distribution, energy management and control systems.",
        icon: "sliders",
        scope: ["Power Management Systems (PMS)", "Variable frequency drives", "Grid bus tie controls"],
      },
      {
        id: "marinepiping",
        slug: "marinepiping",
        domain: "MARINEPIPING.CITY",
        code: "REG 38",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Marine piping, fluid systems, process piping, tanks and related industrial components.",
        shortDescription: "Marine piping, fluid systems, process piping and tanks.",
        icon: "route",
        scope: ["Ballast & bilge piping", "GRE composite pipes", "High-pressure hydraulic lines"],
      },
      {
        id: "decksystems",
        slug: "decksystems",
        domain: "DECKSYSTEMS.CITY",
        code: "REG 39",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Deck machinery, winches, cranes, anchors, windlasses, capstans, mooring systems and related deck equipment.",
        shortDescription: "Deck machinery, winches, cranes and mooring systems.",
        icon: "anchor",
        scope: ["Anchor windlasses & capstans", "Hydraulic deck cranes", "Mooring winch spreads"],
      },
      {
        id: "superyacht",
        slug: "superyacht",
        domain: "SUPERYACHT.CITY",
        code: "REG 40",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Superyacht construction, refit and specialized yacht production.",
        shortDescription: "Superyacht construction, refit and specialized yacht production.",
        icon: "sail",
        scope: ["Custom superyacht builds", "Refit & lengthening", "Specialized yacht outfitting"],
      },
      {
        id: "drydock",
        slug: "drydock",
        domain: "DRYDOCK.CITY",
        code: "REG 41",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Drydock operations, major ship repair, overhaul, conversion and maintenance infrastructure.",
        shortDescription: "Drydock operations, major ship repair, overhaul and conversion.",
        icon: "crane",
        scope: ["Graving dock operations", "Floating dock repair", "Vessel life-extension refit"],
      },
      {
        id: "cleanpropulsion",
        slug: "cleanpropulsion",
        domain: "CLEANPROPULSION.CITY",
        code: "REG 42",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Low-emission, zero-emission and alternative-fuel marine propulsion technologies.",
        shortDescription: "Low-emission, zero-emission and alternative-fuel marine propulsion.",
        icon: "sail",
        scope: ["Methanol & ammonia engines", "Hydrogen fuel cells", "Rotor sails & wind assistance"],
      },
      {
        id: "marinerecycling",
        slug: "marinerecycling",
        domain: "MARINERECYCLING.CITY",
        code: "REG 43",
        industryDomainId: "shipbuilding-production",
        category: "Industrial Products, Equipment & Manufacturing",
        description: "Ship recycling, dismantling and material recovery.",
        shortDescription: "Ship recycling, dismantling and material recovery.",
        icon: "box",
        scope: ["HKC compliant ship recycling", "Steel scrap recovery", "Hazardous material decontamination"],
      },
      {
        id: "marinelogistics",
        slug: "marinelogistics",
        domain: "MARINELOGISTICS.CITY",
        code: "REG 44",
        industryDomainId: "maritime-services",
        category: "Maritime Services, Ports, Marinas & Operations",
        description: "Marine transportation logistics, cargo coordination, freight forwarding and maritime logistics services.",
        shortDescription: "Marine transportation logistics, cargo coordination and freight forwarding.",
        icon: "route",
        scope: ["Cargo coordination", "Freight forwarding", "Maritime logistics services"],
      },
      {
        id: "refit",
        slug: "refit",
        domain: "REFIT.CITY",
        code: "REG 45",
        industryDomainId: "maritime-services",
        category: "Maritime Services, Ports, Marinas & Operations",
        description: "Ship and yacht refit, conversion, modernization and specialized renewal services.",
        shortDescription: "Ship and yacht refit, conversion and modernization services.",
        icon: "crane",
        scope: ["Ship & yacht refits", "Vessel modernization", "Conversion & renewal services"],
      },
      {
        id: "technicalmanagement",
        slug: "technicalmanagement",
        domain: "TECHNICALMANAGEMENT.CITY",
        code: "REG 46",
        industryDomainId: "maritime-services",
        category: "Maritime Services, Ports, Marinas & Operations",
        description: "Technical vessel management, maintenance planning, class coordination, compliance and technical operations.",
        shortDescription: "Technical vessel management, maintenance planning and compliance.",
        icon: "helm",
        scope: ["Technical vessel management", "Class & regulatory compliance", "Planned maintenance systems"],
      },
      {
        id: "vesseloperations",
        slug: "vesseloperations",
        domain: "VESSELOPERATIONS.CITY",
        code: "REG 47",
        industryDomainId: "maritime-services",
        category: "Maritime Services, Ports, Marinas & Operations",
        description: "Vessel operations, voyage execution, operational planning and day-to-day vessel management.",
        shortDescription: "Vessel operations, voyage execution and operational planning.",
        icon: "helm",
        scope: ["Voyage execution", "Day-to-day vessel management", "Operational planning"],
      },
      {
        id: "yachtmanagement",
        slug: "yachtmanagement",
        domain: "YACHTMANAGEMENT.CITY",
        code: "REG 48",
        industryDomainId: "lifestyle-hospitality",
        category: "Yachting, Charter & Maritime Lifestyle",
        description: "Yacht management, owner representation, operational coordination, charter management, crew coordination and yacht administration.",
        shortDescription: "Yacht management, owner representation and operational coordination.",
        icon: "helm",
        scope: ["Owner representation", "Operational & charter management", "Yacht administration"],
      },
      {
        id: "crew",
        slug: "crew",
        domain: "CREW.CITY",
        code: "REG 49",
        industryDomainId: "lifestyle-hospitality",
        category: "Yachting, Charter & Maritime Lifestyle",
        description: "Yacht and maritime crew recruitment, placement, management and professional crew services.",
        shortDescription: "Yacht and maritime crew recruitment, placement and management.",
        icon: "flag",
        scope: ["Crew recruitment & placement", "Maritime crewing management", "Professional crew training"],
      },
      {
        id: "cruise",
        slug: "cruise",
        domain: "CRUISE.CITY",
        code: "REG 50",
        industryDomainId: "lifestyle-hospitality",
        category: "Yachting, Charter & Maritime Lifestyle",
        description: "Cruise operators, cruise lines, cruise vessels, cruise services and cruise experiences.",
        shortDescription: "Cruise operators, cruise lines and cruise experience services.",
        icon: "ship",
        scope: ["Cruise operations & lines", "Onboard guest services", "Cruise vessel management"],
      },
      {
        id: "watercraft",
        slug: "watercraft",
        domain: "WATERCRAFT.CITY",
        code: "REG 51",
        industryDomainId: "lifestyle-hospitality",
        category: "Yachting, Charter & Maritime Lifestyle",
        description: "Recreational watercraft, tenders, personal watercraft, small craft and marine leisure equipment.",
        shortDescription: "Recreational watercraft, tenders, PWCs and marine leisure equipment.",
        icon: "sail",
        scope: ["Tenders & RIBs", "Personal watercraft & jet skis", "Marine water toys & inflatable craft"],
      },
      {
        id: "watersports",
        slug: "watersports",
        domain: "WATERSPORTS.CITY",
        code: "REG 52",
        industryDomainId: "lifestyle-hospitality",
        category: "Yachting, Charter & Maritime Lifestyle",
        description: "Water sports operators, marine recreation, water-based experiences, equipment rental and coastal marine activities.",
        shortDescription: "Water sports operators, marine recreation and equipment rental.",
        icon: "sunrise",
        scope: ["Water sports centres", "Marine equipment rental", "Coastal activity experiences"],
      },
      {
        id: "marinetourism",
        slug: "marinetourism",
        domain: "MARINETOURISM.CITY",
        code: "REG 53",
        industryDomainId: "lifestyle-hospitality",
        category: "Yachting, Charter & Maritime Lifestyle",
        description: "Marine and coastal tourism operators, excursions, cruises, marine experiences and destination services.",
        shortDescription: "Marine & coastal tourism operators, excursions and destination services.",
        icon: "sunrise",
        scope: ["Coastal excursions & tours", "Marine ecotourism", "Destination tour operators"],
      },
      {
        id: "marinedestination",
        slug: "marinedestination",
        domain: "MARINEDESTINATION.CITY",
        code: "REG 54",
        industryDomainId: "lifestyle-hospitality",
        category: "Yachting, Charter & Maritime Lifestyle",
        description: "Marine and coastal destinations, waterfront destination operators, marine experiences and destination services.",
        shortDescription: "Marine & coastal destinations and waterfront destination operators.",
        icon: "pin",
        scope: ["Waterfront destinations", "Coastal hub development", "Marine destination branding"],
      },
      {
        id: "eventsatsea",
        slug: "eventsatsea",
        domain: "EVENTSATSEA.CITY",
        code: "REG 55",
        industryDomainId: "lifestyle-hospitality",
        category: "Yachting, Charter & Maritime Lifestyle",
        description: "Marine events, yacht events, corporate events at sea, regattas and organized marine experiences.",
        shortDescription: "Marine events, yacht events, corporate events at sea and regattas.",
        icon: "flag",
        scope: ["Regatta management", "Corporate marine charters", "Yacht party & event production"],
      },
      {
        id: "luxuryretail",
        slug: "luxuryretail",
        domain: "LUXURYRETAIL.CITY",
        code: "REG 56",
        industryDomainId: "lifestyle-hospitality",
        category: "Yachting, Charter & Maritime Lifestyle",
        description: "Luxury retail serving yacht, marine and coastal lifestyle markets.",
        shortDescription: "Luxury retail serving yacht, marine and coastal lifestyle markets.",
        icon: "box",
        scope: ["Marina luxury boutiques", "Yacht lifestyle retail", "Waterfront luxury shopping"],
      },
      {
        id: "marinefashion",
        slug: "marinefashion",
        domain: "MARINEFASHION.CITY",
        code: "REG 57",
        industryDomainId: "lifestyle-hospitality",
        category: "Yachting, Charter & Maritime Lifestyle",
        description: "Fashion brands, resort wear, marine lifestyle apparel and coastal/yachting fashion.",
        shortDescription: "Fashion brands, resort wear, marine apparel and yachting fashion.",
        icon: "doc",
        scope: ["Yachting apparel", "Coastal resort wear", "Marine technical clothing"],
      },
      {
        id: "marineaccessories",
        slug: "marineaccessories",
        domain: "MARINEACCESSORIES.CITY",
        code: "REG 58",
        industryDomainId: "lifestyle-hospitality",
        category: "Yachting, Charter & Maritime Lifestyle",
        description: "Marine and luxury lifestyle accessories, yacht accessories and coastal leisure products.",
        shortDescription: "Marine and luxury lifestyle accessories and coastal leisure products.",
        icon: "box",
        scope: ["Yacht deck accessories", "Coastal eyewear & timepieces", "Luxury marine gear"],
      },
      {
        id: "luxurygoods",
        slug: "luxurygoods",
        domain: "LUXURYGOODS.CITY",
        code: "REG 59",
        industryDomainId: "lifestyle-hospitality",
        category: "Yachting, Charter & Maritime Lifestyle",
        description: "Premium goods and lifestyle brands serving yacht, marine and coastal markets.",
        shortDescription: "Premium goods and lifestyle brands serving marine markets.",
        icon: "briefcase",
        scope: ["Onboard luxury goods", "Fine spirits & cellar management", "Bespoke marine lifestyle goods"],
      },
      {
        id: "marinedining",
        slug: "marinedining",
        domain: "MARINEDINING.CITY",
        code: "REG 60",
        industryDomainId: "lifestyle-hospitality",
        category: "Yachting, Charter & Maritime Lifestyle",
        description: "Marina dining, waterfront restaurants, yacht club dining, coastal dining and marine destination food experiences.",
        shortDescription: "Marina dining, waterfront restaurants and coastal dining experiences.",
        icon: "dock",
        scope: ["Waterfront restaurants", "Yacht club dining", "Marina gastronomy"],
      },
      {
        id: "beachclub",
        slug: "beachclub",
        domain: "BEACHCLUB.CITY",
        code: "REG 61",
        industryDomainId: "lifestyle-hospitality",
        category: "Yachting, Charter & Maritime Lifestyle",
        description: "Beach clubs and marine/coastal leisure venues connected to yachting and waterfront destinations.",
        shortDescription: "Beach clubs and coastal leisure venues connected to yachting.",
        icon: "sunrise",
        scope: ["Waterfront beach clubs", "Coastal cabanas & lounges", "Yacht destination beach venues"],
      },
      {
        id: "yachtconcierge",
        slug: "yachtconcierge",
        domain: "YACHTCONCIERGE.CITY",
        code: "REG 62",
        industryDomainId: "lifestyle-hospitality",
        category: "Yachting, Charter & Maritime Lifestyle",
        description: "Yacht concierge, VIP guest services, yacht provisioning coordination, private transfers and shore-side concierge.",
        shortDescription: "Yacht concierge, VIP guest services and shore-side assistance.",
        icon: "key",
        scope: ["VIP guest concierge", "Shore-side luxury transfers", "Yacht provisioning coordination"],
      },
      {
        id: "offshorewind",
        slug: "offshorewind",
        domain: "OFFSHOREWIND.CITY",
        code: "REG 63",
        industryDomainId: "offshore-subsea",
        category: "Offshore, Energy & Subsea",
        description: "Offshore wind farms, turbine installation, foundations, subsea cable infrastructure, offshore construction and operations and maintenance.",
        shortDescription: "Offshore wind farms, turbine installation, foundations and cabling.",
        icon: "rig",
        scope: ["Offshore wind farm construction", "Turbine installation & O&M", "Subsea cable laying"],
      },
      {
        id: "oceanenergy",
        slug: "oceanenergy",
        domain: "OCEANENERGY.CITY",
        code: "REG 64",
        industryDomainId: "offshore-subsea",
        category: "Offshore, Energy & Subsea",
        description: "Wave, tidal and other marine renewable energy technologies, projects and services.",
        shortDescription: "Wave, tidal and marine renewable energy technologies.",
        icon: "sonar",
        scope: ["Wave energy converters", "Tidal stream turbines", "Marine renewables R&D"],
      },
      {
        id: "marineinfra",
        slug: "marineinfra",
        domain: "MARINEINFRA.CITY",
        code: "REG 65",
        industryDomainId: "offshore-subsea",
        category: "Offshore, Energy & Subsea",
        description: "Marine infrastructure, coastal structures, marine construction, offshore structures and related civil engineering services.",
        shortDescription: "Marine infrastructure, coastal structures and marine civil works.",
        icon: "crane",
        scope: ["Marine civil engineering", "Breakwaters & seawalls", "Offshore piling & foundations"],
      },
      {
        id: "underwatertech",
        slug: "underwatertech",
        domain: "UNDERWATERTECH.CITY",
        code: "REG 66",
        industryDomainId: "offshore-subsea",
        category: "Offshore, Energy & Subsea",
        description: "Subsea technology, ROVs, AUVs, underwater robotics, sensors, subsea imaging and intervention equipment.",
        shortDescription: "ROVs, AUVs, underwater robotics, subsea sensors and imaging.",
        icon: "sonar",
        scope: ["Work-class ROVs & AUVs", "Subsea acoustic sensors", "Underwater imaging & telemetry"],
      },
      {
        id: "villa",
        slug: "villa",
        domain: "VILLA.CITY",
        code: "REG 67",
        industryDomainId: "lifestyle-hospitality",
        category: "Real Estate & Hospitality",
        description: "Waterfront villas, marina-area villas, luxury coastal villas, villa sales, villa rentals and marine-connected residential property.",
        shortDescription: "Waterfront villas, marina-area villas and coastal villa rentals.",
        icon: "building",
        scope: ["Waterfront luxury villas", "Marina villa rentals & sales", "Coastal private estates"],
      },
      {
        id: "residence",
        slug: "residence",
        domain: "RESIDENCE.CITY",
        code: "REG 68",
        industryDomainId: "lifestyle-hospitality",
        category: "Real Estate & Hospitality",
        description: "Residential developments, serviced residences, branded residences, luxury residential projects and apartment-based marine/waterfront living.",
        shortDescription: "Serviced & branded residential developments and waterfront apartments.",
        icon: "building",
        scope: ["Branded marine residences", "Serviced waterfront apartments", "Luxury residential developments"],
      },
      {
        id: "waterfrontrealestate",
        slug: "waterfrontrealestate",
        domain: "WATERFRONTREALESTATE.CITY",
        code: "REG 69",
        industryDomainId: "lifestyle-hospitality",
        category: "Real Estate & Hospitality",
        description: "Waterfront property, marina-adjacent property, coastal commercial property, mixed-use waterfront developments and marine-connected real estate investment.",
        shortDescription: "Waterfront property, marina-adjacent real estate and coastal investment.",
        icon: "building",
        scope: ["Waterfront commercial property", "Marina-adjacent real estate", "Coastal land & property investment"],
      },
      {
        id: "marinadevelopment",
        slug: "marinadevelopment",
        domain: "MARINADEVELOPMENT.CITY",
        code: "REG 70",
        industryDomainId: "lifestyle-hospitality",
        category: "Real Estate & Hospitality",
        description: "Marina development, marina expansion, waterfront masterplans, mixed-use marina projects, yacht harbor development and marine-connected real estate investment projects.",
        shortDescription: "Marina expansion, masterplanning and harbor development projects.",
        icon: "crane",
        scope: ["Marina masterplanning", "Harbor expansion projects", "Mixed-use marina development"],
      },
      {
        id: "hotel",
        slug: "hotel",
        domain: "HOTEL.CITY",
        code: "REG 71",
        industryDomainId: "lifestyle-hospitality",
        category: "Real Estate & Hospitality",
        description: "Marine destinations, marina hotels, waterfront hotels, yacht-destination accommodation and port-area hospitality.",
        shortDescription: "Marina hotels, waterfront accommodation and port hospitality.",
        icon: "building",
        scope: ["Marina waterfront hotels", "Port-area business hospitality", "Yacht destination lodging"],
      },
      {
        id: "resort",
        slug: "resort",
        domain: "RESORT.CITY",
        code: "REG 72",
        industryDomainId: "lifestyle-hospitality",
        category: "Real Estate & Hospitality",
        description: "Marina resorts, waterfront resorts, coastal luxury resorts, yacht destination resorts and integrated marine resorts.",
        shortDescription: "Marina resorts, coastal luxury resorts and integrated marine destinations.",
        icon: "sunrise",
        scope: ["Integrated marina resorts", "Coastal luxury beach resorts", "Yacht destination resorts"],
      },
      {
        id: "registries",
        slug: "registries",
        domain: "REGISTRIES.CITY",
        code: "REG 73",
        industryDomainId: "governance",
        category: "Industry Governance, Associations & Clusters",
        description: "Flag-state registries, ship registries, maritime administrations and vessel registration bodies.",
        shortDescription: "Flag-state registries, ship registries and maritime administrations.",
        icon: "flag",
        scope: ["Flag-state vessel registration", "International ship registries", "Maritime administrative compliance"],
      },
      {
        id: "governance",
        slug: "governance",
        domain: "GOVERNANCE.CITY",
        code: "REG 74",
        industryDomainId: "governance",
        category: "Industry Governance, Associations & Clusters",
        description: "Maritime industry governance, policy frameworks, regulatory standards and institutional oversight.",
        shortDescription: "Maritime industry governance, policy frameworks and regulatory standards.",
        icon: "shield",
        scope: ["Maritime regulatory oversight", "International policy frameworks", "Industry compliance standards"],
      },
      {
        id: "identity",
        slug: "identity",
        domain: "IDENTITY.CITY",
        code: "REG 75",
        industryDomainId: "governance",
        category: "Industry Governance, Associations & Clusters",
        description: "Maritime institutional verification, corporate identity, official accreditations and trust architecture.",
        shortDescription: "Maritime institutional verification, corporate identity and trust architecture.",
        icon: "shield",
        scope: ["Verified corporate identity", "Official industry accreditations", "Trust & verification ledgers"],
      },
      {
        id: "ecosystem",
        slug: "ecosystem",
        domain: "ECOSYSTEM.CITY",
        code: "REG 76",
        industryDomainId: "governance",
        category: "Industry Governance, Associations & Clusters",
        description: "Maritime ecosystem hubs, organizational networks, institutional member programs and platform ecosystem management.",
        shortDescription: "Maritime ecosystem hubs, organizational networks and member programs.",
        icon: "layers",
        scope: ["Organizational ecosystem hubs", "Member enrollment & verification", "Ecosystem network management"],
      },
      {
        id: "associations",
        slug: "associations",
        domain: "ASSOCIATIONS.CITY",
        code: "REG 77",
        industryDomainId: "governance",
        category: "Industry Governance, Associations & Clusters",
        description: "Maritime trade associations, professional bodies, shipowner associations, yacht associations and marine industry organizations.",
        shortDescription: "Maritime trade associations, professional bodies and industry organizations.",
        icon: "flag",
        scope: ["Trade & professional bodies", "Shipowner & yacht associations", "Marine industry networking"],
      },
      {
        id: "chambers",
        slug: "chambers",
        domain: "CHAMBERS.CITY",
        code: "REG 78",
        industryDomainId: "governance",
        category: "Industry Governance, Associations & Clusters",
        description: "Maritime chambers of commerce, regional shipping chambers, port chambers and commercial marine trade bodies.",
        shortDescription: "Maritime chambers of commerce, shipping chambers and trade bodies.",
        icon: "building",
        scope: ["Maritime chambers of commerce", "Regional shipping chambers", "Port & commercial trade bodies"],
      },
      {
        id: "clusters",
        slug: "clusters",
        domain: "CLUSTERS.CITY",
        code: "REG 79",
        industryDomainId: "governance",
        category: "Industry Governance, Associations & Clusters",
        description: "Regional maritime clusters, shipbuilding clusters, marine technology hubs and coastal industrial ecosystems.",
        shortDescription: "Regional maritime clusters, technology hubs and industrial ecosystems.",
        icon: "pin",
        scope: ["Regional maritime clusters", "Shipbuilding & tech hubs", "Coastal industrial ecosystems"],
      },
      {
        id: "compliance",
        slug: "compliance",
        domain: "COMPLIANCE.CITY",
        code: "REG 80",
        industryDomainId: "finance-legal",
        category: "Legal, Finance & Compliance",
        description: "Maritime regulatory, operational, environmental and certification compliance services.",
        shortDescription: "Maritime regulatory, operational and environmental compliance services.",
        icon: "shield",
        scope: ["Regulatory compliance audits", "Environmental & safety standards", "Statutory operational compliance"],
      },
      {
        id: "classification",
        slug: "classification",
        domain: "CLASSIFICATION.CITY",
        code: "REG 81",
        industryDomainId: "finance-legal",
        category: "Legal, Finance & Compliance",
        description: "Vessel classification, statutory certification, technical surveys, inspections and class compliance services.",
        shortDescription: "Vessel classification, statutory certification and technical surveys.",
        icon: "shield",
        scope: ["Vessel class certification", "Statutory marine surveys", "Technical inspection services"],
      },
      {
        id: "flagregistry",
        slug: "flagregistry",
        domain: "FLAGREGISTRY.CITY",
        code: "REG 82",
        industryDomainId: "finance-legal",
        category: "Legal, Finance & Compliance",
        description: "Vessel registration services, flag administration advisory, documentation and flag-state compliance.",
        shortDescription: "Vessel registration services, flag advisory and documentation.",
        icon: "flag",
        scope: ["Vessel registration services", "Flag administration advisory", "Title & documentation compliance"],
      },
    ],
  },

  network: {
    eyebrow: "Business Ecosystem",
    headline: "THE BUSINESSES BEHIND THE INDUSTRY.",
    lead: "MarineWorld connects companies and their operational capabilities — what they build, operate, supply, finance and insure. Each profile is a structured business entity, ready for discovery, verification and AI-native interaction.",
    demoNotice: "Live registry data is served through the platform data layer.",
    companies: [],
  },


  ai: {
    eyebrow: "AI-Native Business Layer",
    headline: "THE INDUSTRY, READY FOR AI.",
    lead: "On MarineWorld, AI is business infrastructure — not a chatbot window. Every company can operate an AI-native surface, grounded in its own verified information, connected to the industry network and built for real commercial interaction.",
    capabilities: [
      {
        id: "company-info",
        title: "Company Information",
        description: "Structured answers about identity, scope and capabilities.",
        icon: "building",
      },
      {
        id: "product-info",
        title: "Product Information",
        description: "Catalogue intelligence across marine products and parts.",
        icon: "cube",
      },
      {
        id: "specs",
        title: "Technical Specifications",
        description: "Specifications served directly from company-held data.",
        icon: "drafting",
      },
      {
        id: "discovery",
        title: "Service Discovery",
        description: "Find the right service, supplier or yard by capability.",
        icon: "compass",
      },
      {
        id: "inquiries",
        title: "Business Inquiries",
        description: "Inquiries received, qualified and answered around the clock.",
        icon: "connect",
      },
      {
        id: "rfq",
        title: "RFQs",
        description: "Structured requests routed to capable, verified suppliers.",
        icon: "doc",
      },
      {
        id: "navigation",
        title: "Industry Navigation",
        description: "Move across cities, regions and sectors with intent.",
        icon: "globe",
      },
      {
        id: "workflows",
        title: "Operational Workflows",
        description: "AI embedded in the operational flow of maritime business.",
        icon: "gauge",
      },
    ],
    twin: {
      eyebrow: "Company Business Twin",
      headline: "EVERY COMPANY CAN HAVE A BUSINESS TWIN.",
      body: "A MarineWorld business twin is the AI representation of a business — grounded in company-provided information and operational context. It speaks for the company, serves its data and handles interaction, while the company stays in control of what it knows and says. This is a platform capability that companies activate — not an assumption that every company already has one.",
      points: [
        "Grounded in verified, company-provided data",
        "Aware of operational context — capabilities, coverage, availability",
        "Connected to the industry network, not isolated in a chat window",
        "Built for business interaction: inquiries, RFQs, specifications",
      ],
      chain: [
        { id: "company", label: "Company", status: "Entity verified", icon: "building" },
        { id: "twin", label: "AI Twin", status: "Twin active — grounded in registry data", icon: "twin" },
        { id: "network", label: "Industry Network", status: "Connected across city registries", icon: "network" },
        { id: "interaction", label: "Business Interaction", status: "Inquiry · RFQ · Match · Specification", icon: "exchange" },
      ],
    },
  },

  regions: {
    eyebrow: "Global Industry Coverage",
    headline: "ONE MARITIME INDUSTRY. GLOBAL REACH.",
    lead: "MarineWorld is structured around the geography of the maritime industry itself — twelve regional registries that organize companies, cities and services where the industry actually operates.",
    note: "Regional registries are structural coverage — the taxonomy the platform is built on — not a claim of completed listings in every market.",
    items: [
      {
        id: "med",
        code: "R-01",
        name: "Mediterranean",
        x: 53.5,
        y: 24.5,
        description:
          "The yachting and refit heart of the industry — marinas, charter fleets, shipyards and a dense service economy along three continents.",
        focus: ["MARINA.CITY", "CHARTER.CITY", "SHIPYARD.CITY"],
      },
      {
        id: "southern-europe",
        code: "R-02",
        name: "Southern Europe",
        x: 49,
        y: 21,
        description:
          "Boatbuilding traditions, Adriatic refit clusters and Mediterranean gateway ports.",
        focus: ["BOATBUILDING.CITY", "ENGINEERING.CITY"],
      },
      {
        id: "western-europe",
        code: "R-03",
        name: "Western Europe",
        x: 45.5,
        y: 17,
        description:
          "Europe's commercial spine — major ports, marine engineering houses and maritime finance.",
        focus: ["PORT.CITY", "ENGINEERING.CITY", "MARINELEGAL.CITY"],
      },
      {
        id: "northern-europe",
        code: "R-04",
        name: "Northern Europe",
        x: 50,
        y: 12,
        description:
          "Advanced shipbuilding, offshore energy and maritime technology leadership.",
        focus: ["OFFSHORE.CITY", "AUTONOMOUSVESSEL.CITY"],
      },
      {
        id: "eastern-europe",
        code: "R-05",
        name: "Eastern Europe & Caucasus",
        x: 58.5,
        y: 17,
        description:
          "Black Sea shipbuilding, river-sea trade and emerging marine services.",
        focus: ["SHIPYARD.CITY", "MARINECOMMERCE.CITY"],
      },
      {
        id: "north-america",
        code: "R-06",
        name: "North America",
        x: 20,
        y: 18,
        description:
          "Coastal workboat industries, Great Lakes shipping and marine technology ventures.",
        focus: ["FLEETMANAGEMENT.CITY", "MARINEAI.CITY"],
      },
      {
        id: "central-south-america",
        code: "R-07",
        name: "Central & South America",
        x: 30,
        y: 42,
        description:
          "Growing port infrastructure, fisheries support and coastal trade corridors.",
        focus: ["PORT.CITY", "SUPPLYCHAIN.CITY"],
      },
      {
        id: "caribbean",
        code: "R-08",
        name: "Caribbean",
        x: 26,
        y: 29,
        description:
          "Charter seasons, superyacht service hubs and island marina networks.",
        focus: ["CHARTER.CITY", "MARINEHOSPITALITY.CITY"],
      },
      {
        id: "middle-east",
        code: "R-09",
        name: "Middle East",
        x: 61,
        y: 27,
        description:
          "Gulf mega-marinas, trade logistics and large-scale maritime development.",
        focus: ["MARINA.CITY", "YACHTSALES.CITY"],
      },
      {
        id: "asia",
        code: "R-10",
        name: "Asia",
        x: 72,
        y: 24,
        description:
          "The world's shipbuilding center and its busiest container corridors.",
        focus: ["SHIPYARD.CITY", "SUPPLYCHAIN.CITY", "PORT.CITY"],
      },
      {
        id: "africa",
        code: "R-11",
        name: "Africa",
        x: 51,
        y: 36,
        description:
          "Strategic shipping lanes, port growth and offshore energy frontiers.",
        focus: ["PORT.CITY", "OFFSHORE.CITY"],
      },
      {
        id: "pacific",
        code: "R-12",
        name: "Pacific Islands & Australasia",
        x: 84,
        y: 42,
        description:
          "Blue-economy leadership, expedition fleets and Pacific passage services.",
        focus: ["MARINELIFESTYLE.CITY", "FLEETMANAGEMENT.CITY"],
      },
    ],
  },

  workflow: {
    eyebrow: "Business Interaction",
    headline: "FROM DISCOVERY TO BUSINESS INTERACTION.",
    lead: "MarineWorld is built as an operational flow — moving the industry from fragmented searching into structured business interaction, one continuous path.",
    steps: [
      {
        id: "discover",
        index: "01",
        title: "Discover",
        description:
          "Search the industry by capability, product, service or city — across the full registry, not a single vendor list.",
        example: "Find refit yards in the Mediterranean",
        icon: "search",
      },
      {
        id: "identify",
        index: "02",
        title: "Identify",
        description:
          "Evaluate structured company profiles — verification status, operational scope and capabilities, side by side.",
        example: "Compare verified shipyards by capacity",
        icon: "scan",
      },
      {
        id: "connect",
        index: "03",
        title: "Connect",
        description:
          "Open a direct, authenticated channel to the business — company to company, buyer to supplier, owner to yard.",
        example: "Request introduction to a marine engineer",
        icon: "connect",
      },
      {
        id: "interact",
        index: "04",
        title: "Interact",
        description:
          "Engage the company's AI-native surface for specifications, availability and immediate, grounded answers.",
        example: "Ask a company's AI twin for technical specs",
        icon: "twin",
      },
      {
        id: "request",
        index: "05",
        title: "Request",
        description:
          "Issue structured RFQs and service requests that arrive complete — scope, context and requirements attached.",
        example: "Publish an RFQ to qualified suppliers",
        icon: "doc",
      },
      {
        id: "collaborate",
        index: "06",
        title: "Collaborate",
        description:
          "Move into delivery with shared operational context between businesses — projects, not lost email threads.",
        example: "Coordinate a refit project across suppliers",
        icon: "crew",
      },
    ],
  },

  governance: {
    eyebrow: "Trust & Governance",
    headline: "GOVERNANCE BUILT FOR INDUSTRY.",
    lead: "MarineWorld operates as a governed business ecosystem. Trust is not a badge you buy — it is a structure: identities are issued, verified and auditable, and AI operates under defined rules.",
    pillars: [
      {
        id: "identity",
        title: "Identity",
        description: "Every business entity holds a structured corporate identity issued within the platform.",
        icon: "key",
      },
      {
        id: "verification",
        title: "Verification",
        description: "Company claims pass through verification before they appear as trust signals in the registry.",
        icon: "scan",
      },
      {
        id: "security",
        title: "Security",
        description: "Access to company data follows authorization boundaries — public registry, private operations.",
        icon: "lock",
      },
      {
        id: "data",
        title: "Operational Data",
        description: "Companies control what operational data is shared, with whom, and for which interactions.",
        icon: "database",
      },
      {
        id: "ai-governance",
        title: "AI Governance",
        description: "AI twins answer from company-held, company-approved information — not from the open web.",
        icon: "sliders",
      },
    ],
    note: "MarineWorld is an enterprise ecosystem: factual governance, explicit verification states and no inflated claims.",
  },

  cta: {
    eyebrow: "Enter MarineWorld",
    headline: "ENTER THE MARITIME BUSINESS CITY.",
    body: "Explore companies, capabilities, services and industry intelligence across the global marine and maritime ecosystem — one intelligent digital environment.",
    primary: "Explore MarineWorld",
    secondary: "Register Your Business",
  },

  footer: {
    blurb:
      "The digital business city for the global marine industry. Companies, products, services and commercial opportunities — connected in one industry environment.",
    infrastructure: "Powered by the UNIVABIL Protocol™.",
    columns: [
      {
        title: "Explore",
        links: [
          { label: "City Explorer", href: "#explorer" },
          { label: "Global Coverage", href: "#global" },
          { label: "Business Workflow", href: "#workflow" },
        ],
      },
      {
        title: "Business",
        links: [
          { label: "Companies", href: "#network" },
          { label: "Register Your Business", href: "#enter" },
          { label: "Getting Started Guide", href: "/getting-started" },
        ],
      },
      {
        title: "AI",
        links: [
          { label: "Company AI", href: "#ai" },
          { label: "AI Advisors", href: "#ai" },
          { label: "AI Governance", href: "#governance" },
        ],
      },
      {
        title: "Company",
        links: [
          { label: "About", href: "#governance" },
          { label: "Sector City Framework", href: "/sectors" },
          { label: "Contact & Secretariat", href: "/contact" },
        ],
      },
      {
        title: "Legal",
        links: [
          { label: "Terms of Service", href: "/terms" },
          { label: "Privacy Policy", href: "/privacy" },
          { label: "Security Framework", href: "/security" },
          { label: "Cookie Policy", href: "/cookies" },
        ],
      },
    ],
    legalLine: "A DigiOne Sector City · MarineWorld.City",
  },
};
